version: "3"

services:
  horizon:
    image: stellar/quickstart
    ports:
      - 8000:8000
      - 11626:11626
    volumes:
      - ./run/horizon:/opt/stellar
      - ./run/log:/var/log/supervisor
    environment:
      - PGPASS=1
      - NETWORK=testnet
      # - NETWORK=pubnet
